import { Product } from "./types";

const seasonalDisclaimer = {
  ru: "Итоговая композиция совпадает с каталогом на 95-99%. Возможны минимальные сезонные отличия в оттенках и сортах цветов, не нарушающие общую геометрию, характер и премиальный уровень букета.",
  en: "The final arrangement will correspond to the catalogue design by approximately 95-99%. Minor seasonal variations in flower varieties and shades may occur without changing the overall shape, character or premium standard of the bouquet.",
  it: "La composizione finale corrispondera al modello del catalogo per circa il 95-99%. Sono possibili minime variazioni stagionali nelle varieta e nelle tonalita dei fiori, senza modificare la geometria, il carattere o il livello premium del bouquet."
};

const care = {
  ru: "Снимите транспортировочную упаковку, обновите срез и поставьте цветы в чистую прохладную воду вдали от прямого солнца.",
  en: "Remove the transport wrap, refresh the stems and place the flowers in clean cool water away from direct sun.",
  it: "Rimuovere l'imballo da trasporto, rinnovare il taglio e sistemare i fiori in acqua fresca e pulita, lontano dal sole diretto."
};

export const products: Product[] = [
  {
    id: "p-001",
    slug: "como-morning",
    title: { ru: "Утро в Комо", en: "Como Morning", it: "Mattina a Como" },
    shortDescription: { ru: "Легкий авторский букет в бело-голубой гамме.", en: "A light signature bouquet in white and blue tones.", it: "Un bouquet d'autore leggero nei toni del bianco e dell'azzurro." },
    fullDescription: { ru: "Свежая композиция для утренней доставки, камерного поздравления или изящного жеста.", en: "A fresh arrangement for morning delivery, intimate congratulations or an elegant gesture.", it: "Una composizione fresca per una consegna mattutina, un augurio intimo o un gesto elegante." },
    exactPrice: 120,
    images: ["/assets/products/generated/blue-white-bouquet.png"],
    categories: ["signature", "seasonal"],
    flowerComposition: { ru: "Розы, эустома, сезонная зелень.", en: "Roses, lisianthus and seasonal greenery.", it: "Rose, lisianthus e verde di stagione." },
    sizeDescription: { ru: "Компактный букет, около 35 см.", en: "Compact bouquet, around 35 cm.", it: "Bouquet compatto, circa 35 cm." },
    careInstructions: care,
    seasonalDisclaimer,
    featured: true,
    available: true,
    madeToOrder: false,
    minimumLeadTimeHours: 24,
    seoTitle: { ru: "Утро в Комо - букет", en: "Como Morning bouquet", it: "Bouquet Mattina a Como" },
    seoDescription: { ru: "Авторский букет с доставкой по Комо.", en: "Signature bouquet with delivery across Como.", it: "Bouquet d'autore con consegna a Como." }
  },
  {
    id: "p-002",
    slug: "silk-lake",
    title: { ru: "Шелковое озеро", en: "Silk Lake", it: "Lago di Seta" },
    shortDescription: { ru: "Деликатная композиция с мягким силуэтом.", en: "A delicate arrangement with a soft silhouette.", it: "Una composizione delicata dalla silhouette morbida." },
    fullDescription: { ru: "Создана для спокойных, очень личных моментов и адресных поздравлений.", en: "Created for calm, deeply personal moments and thoughtful greetings.", it: "Creata per momenti quieti, personali e auguri pensati con cura." },
    exactPrice: 145,
    images: ["/assets/products/generated/pink-ivory-arrangement.png"],
    categories: ["signature", "gifts"],
    flowerComposition: { ru: "Камелии, ранункулюсы, нежная зелень.", en: "Camellias, ranunculus and soft greenery.", it: "Camelie, ranuncoli e verde leggero." },
    sizeDescription: { ru: "Компактная композиция, около 40 см.", en: "Compact arrangement, around 40 cm.", it: "Composizione compatta, circa 40 cm." },
    careInstructions: care,
    seasonalDisclaimer,
    featured: true,
    available: true,
    madeToOrder: false,
    minimumLeadTimeHours: 24,
    seoTitle: { ru: "Шелковое озеро - букет", en: "Silk Lake bouquet", it: "Bouquet Lago di Seta" },
    seoDescription: { ru: "Деликатная композиция MUZA.", en: "A delicate MUZA arrangement.", it: "Una composizione delicata MUZA." }
  },
  {
    id: "p-003",
    slug: "white-camellia",
    title: { ru: "Белая камелия", en: "White Camellia", it: "Camelia Bianca" },
    shortDescription: { ru: "Утонченный белый букет для элегантного жеста.", en: "A refined white bouquet for an elegant gesture.", it: "Un raffinato bouquet bianco per un gesto elegante." },
    fullDescription: { ru: "Чистый, собранный образ с мягким объемом и воздушной графикой.", en: "A pure, composed design with gentle volume and airy line.", it: "Un disegno puro e composto, con volume lieve e linea ariosa." },
    exactPrice: 170,
    images: ["/assets/products/generated/blue-white-bouquet.png"],
    categories: ["signature", "roses"],
    flowerComposition: { ru: "Белые розы, камелии, сезонные акценты.", en: "White roses, camellias and seasonal accents.", it: "Rose bianche, camelie e accenti stagionali." },
    sizeDescription: { ru: "Средний букет, около 45 см.", en: "Medium bouquet, around 45 cm.", it: "Bouquet medio, circa 45 cm." },
    careInstructions: care,
    seasonalDisclaimer,
    featured: true,
    available: true,
    madeToOrder: false,
    minimumLeadTimeHours: 24,
    seoTitle: { ru: "Белая камелия - букет", en: "White Camellia bouquet", it: "Bouquet Camelia Bianca" },
    seoDescription: { ru: "Белый авторский букет на озере Комо.", en: "White signature bouquet on Lake Como.", it: "Bouquet bianco d'autore sul Lago di Como." }
  },
  {
    id: "p-004",
    slug: "blevio-air",
    title: { ru: "Воздух Блевио", en: "Blevio Air", it: "Aria di Blevio" },
    shortDescription: { ru: "Легкая пастельная композиция среднего масштаба.", en: "A light pastel arrangement of medium scale.", it: "Una composizione pastello leggera di media dimensione." },
    fullDescription: { ru: "Композиция с прозрачным ритмом, созданная для частной виллы, отеля или ужина у озера.", en: "An arrangement with a transparent rhythm, created for a private villa, hotel or dinner by the lake.", it: "Una composizione dal ritmo trasparente, creata per villa privata, hotel o cena sul lago." },
    exactPrice: 190,
    images: ["/assets/products/generated/blue-floral-box.png"],
    categories: ["seasonal", "table"],
    flowerComposition: { ru: "Гортензия, розы, сезонная зелень.", en: "Hydrangea, roses and seasonal greenery.", it: "Ortensia, rose e verde di stagione." },
    sizeDescription: { ru: "Средняя композиция, около 50 см.", en: "Medium arrangement, around 50 cm.", it: "Composizione media, circa 50 cm." },
    careInstructions: care,
    seasonalDisclaimer,
    featured: false,
    available: true,
    madeToOrder: true,
    minimumLeadTimeHours: 36,
    seoTitle: { ru: "Воздух Блевио", en: "Blevio Air", it: "Aria di Blevio" },
    seoDescription: { ru: "Пастельная композиция MUZA.", en: "Pastel arrangement by MUZA.", it: "Composizione pastello MUZA." }
  },
  {
    id: "p-005",
    slug: "bellagio-garden",
    title: { ru: "Сад Белладжо", en: "Bellagio Garden", it: "Giardino di Bellagio" },
    shortDescription: { ru: "Щедрый букет с выразительным ботаническим характером.", en: "A generous bouquet with expressive botanical character.", it: "Un bouquet generoso dal carattere botanico espressivo." },
    fullDescription: { ru: "Большой букет для особого подарка, семейного торжества или приветствия гостей.", en: "A large bouquet for a special gift, family celebration or guest welcome.", it: "Un grande bouquet per un regalo importante, una festa di famiglia o un benvenuto agli ospiti." },
    exactPrice: 240,
    images: ["/assets/products/generated/white-villa-arrangement.png"],
    categories: ["signature", "seasonal"],
    flowerComposition: { ru: "Пионы, садовые розы, эвкалипт.", en: "Peonies, garden roses and eucalyptus.", it: "Peonie, rose da giardino ed eucalipto." },
    sizeDescription: { ru: "Большой букет, около 60 см.", en: "Large bouquet, around 60 cm.", it: "Grande bouquet, circa 60 cm." },
    careInstructions: care,
    seasonalDisclaimer,
    featured: true,
    available: true,
    madeToOrder: true,
    minimumLeadTimeHours: 36,
    seoTitle: { ru: "Сад Белладжо", en: "Bellagio Garden", it: "Giardino di Bellagio" },
    seoDescription: { ru: "Объемный букет для доставки по озеру Комо.", en: "A generous bouquet for delivery around Lake Como.", it: "Un bouquet generoso con consegna sul Lago di Como." }
  },
  {
    id: "p-006",
    slug: "villa-carlotta",
    title: { ru: "Вилла Карлотта", en: "Villa Carlotta", it: "Villa Carlotta" },
    shortDescription: { ru: "Пышная садовая композиция с архитектурной линией.", en: "A lush garden arrangement with architectural line.", it: "Una composizione da giardino rigogliosa con linea architettonica." },
    fullDescription: { ru: "Объемный букет с праздничной пластикой и мягкой фактурой лепестков.", en: "A voluminous bouquet with celebratory movement and soft petal texture.", it: "Un bouquet voluminoso dal movimento festoso e dalla texture morbida." },
    exactPrice: 285,
    images: ["/assets/products/generated/pink-ivory-arrangement.png"],
    categories: ["roses", "gifts"],
    flowerComposition: { ru: "Садовые розы, дельфиниум, сезонные ветви.", en: "Garden roses, delphinium and seasonal branches.", it: "Rose da giardino, delphinium e rami stagionali." },
    sizeDescription: { ru: "Большой букет, около 65 см.", en: "Large bouquet, around 65 cm.", it: "Grande bouquet, circa 65 cm." },
    careInstructions: care,
    seasonalDisclaimer,
    featured: true,
    available: true,
    madeToOrder: true,
    minimumLeadTimeHours: 48,
    seoTitle: { ru: "Вилла Карлотта", en: "Villa Carlotta bouquet", it: "Bouquet Villa Carlotta" },
    seoDescription: { ru: "Садовый букет премиального масштаба.", en: "A garden bouquet of premium scale.", it: "Un bouquet da giardino di alta presenza." }
  },
  {
    id: "p-007",
    slug: "blue-hour",
    title: { ru: "Голубой час", en: "Blue Hour", it: "Ora Blu" },
    shortDescription: { ru: "Графичная композиция в фарфорово-голубой гамме.", en: "A graphic arrangement in porcelain-blue tones.", it: "Una composizione grafica nei toni azzurro porcellana." },
    fullDescription: { ru: "Сдержанный, выразительный подарок для вечера, ужина или события у воды.", en: "A restrained, expressive gift for an evening, dinner or lakeside event.", it: "Un regalo misurato ed espressivo per una serata, una cena o un evento sull'acqua." },
    exactPrice: 330,
    images: ["/assets/products/generated/blue-floral-box.png"],
    categories: ["floral-boxes", "table"],
    flowerComposition: { ru: "Ирисы, белые розы, декоративная зелень.", en: "Irises, white roses and decorative greenery.", it: "Iris, rose bianche e verde decorativo." },
    sizeDescription: { ru: "Крупная композиция, около 70 см.", en: "Statement arrangement, around 70 cm.", it: "Composizione importante, circa 70 cm." },
    careInstructions: care,
    seasonalDisclaimer,
    featured: true,
    available: true,
    madeToOrder: true,
    minimumLeadTimeHours: 48,
    seoTitle: { ru: "Голубой час", en: "Blue Hour arrangement", it: "Composizione Ora Blu" },
    seoDescription: { ru: "Фарфорово-голубая композиция MUZA.", en: "Porcelain-blue arrangement by MUZA.", it: "Composizione azzurro porcellana MUZA." }
  },
  {
    id: "p-008",
    slug: "the-cernobbio",
    title: { ru: "Черноббио", en: "The Cernobbio", it: "Il Cernobbio" },
    shortDescription: { ru: "Статусный букет для виллы, отеля или торжества.", en: "A statement bouquet for a villa, hotel or celebration.", it: "Un bouquet d'impatto per villa, hotel o celebrazione." },
    fullDescription: { ru: "Собранный, масштабный образ с богатой сезонной фактурой.", en: "A composed, generous design with rich seasonal texture.", it: "Un disegno composto e generoso con ricca texture stagionale." },
    exactPrice: 420,
    images: ["/assets/products/generated/white-villa-arrangement.png"],
    categories: ["signature", "gifts"],
    flowerComposition: { ru: "Пионы, розы, орхидеи, ветви.", en: "Peonies, roses, orchids and branches.", it: "Peonie, rose, orchidee e rami." },
    sizeDescription: { ru: "Масштабный букет, около 80 см.", en: "Large-scale bouquet, around 80 cm.", it: "Bouquet di grande scala, circa 80 cm." },
    careInstructions: care,
    seasonalDisclaimer,
    featured: false,
    available: true,
    madeToOrder: true,
    minimumLeadTimeHours: 48,
    seoTitle: { ru: "Черноббио", en: "The Cernobbio bouquet", it: "Bouquet Il Cernobbio" },
    seoDescription: { ru: "Масштабный букет для особого адресата.", en: "A large-scale bouquet for a special recipient.", it: "Un grande bouquet per un destinatario speciale." }
  },
  {
    id: "p-009",
    slug: "villa-evening",
    title: { ru: "Вечер на вилле", en: "Villa Evening", it: "Sera in Villa" },
    shortDescription: { ru: "Настольная композиция для ужина и приема гостей.", en: "A table arrangement for dinner and guest reception.", it: "Una composizione da tavola per cena e accoglienza." },
    fullDescription: { ru: "Низкая композиция с мягкой линией, созданная для сервировки без визуального шума.", en: "A low arrangement with a soft line, created for tablescapes without visual noise.", it: "Una composizione bassa e morbida, pensata per la tavola senza rumore visivo." },
    exactPrice: 360,
    images: ["/assets/products/generated/pink-ivory-arrangement.png"],
    categories: ["table", "events"],
    flowerComposition: { ru: "Садовые розы, гортензия, зелень.", en: "Garden roses, hydrangea and greenery.", it: "Rose da giardino, ortensia e verde." },
    sizeDescription: { ru: "Низкая настольная композиция, 65 см.", en: "Low table arrangement, 65 cm.", it: "Composizione bassa da tavola, 65 cm." },
    careInstructions: care,
    seasonalDisclaimer,
    featured: false,
    available: true,
    madeToOrder: true,
    minimumLeadTimeHours: 48,
    seoTitle: { ru: "Вечер на вилле", en: "Villa Evening table flowers", it: "Fiori da tavola Sera in Villa" },
    seoDescription: { ru: "Композиция для ужина на озере Комо.", en: "Arrangement for a Lake Como dinner.", it: "Composizione per una cena sul Lago di Como." }
  },
  {
    id: "p-010",
    slug: "lario-atelier",
    title: { ru: "Ателье Ларио", en: "Lario Atelier", it: "Atelier Lario" },
    shortDescription: { ru: "Индивидуальная композиция высокого флористического искусства.", en: "A bespoke composition of high floral craft.", it: "Una composizione su misura di alta arte floreale." },
    fullDescription: { ru: "Персональная работа для VIP-подарка, частного ужина или оформления пространства.", en: "A personal commission for a VIP gift, private dinner or spatial floral statement.", it: "Una commissione personale per regalo VIP, cena privata o installazione floreale." },
    exactPrice: 560,
    images: ["/assets/products/generated/white-villa-arrangement.png"],
    categories: ["bespoke", "events"],
    flowerComposition: { ru: "Состав подбирается индивидуально после консультации.", en: "Composition is selected individually after consultation.", it: "La composizione viene definita individualmente dopo una consulenza." },
    sizeDescription: { ru: "Индивидуальный масштаб.", en: "Bespoke scale.", it: "Dimensione su misura." },
    careInstructions: care,
    seasonalDisclaimer,
    featured: true,
    available: true,
    madeToOrder: true,
    minimumLeadTimeHours: 72,
    seoTitle: { ru: "Ателье Ларио", en: "Lario Atelier bespoke flowers", it: "Fiori su misura Atelier Lario" },
    seoDescription: { ru: "Индивидуальная флористика на озере Комо.", en: "Bespoke floristry on Lake Como.", it: "Floristica su misura sul Lago di Como." }
  },
  {
    id: "p-011",
    slug: "villa-guest",
    title: { ru: "Гость виллы", en: "Villa Guest", it: "Ospite in Villa" },
    shortDescription: { ru: "Эффектная композиция для приветствия гостей.", en: "A striking arrangement for welcoming guests.", it: "Una composizione scenografica per accogliere gli ospiti." },
    fullDescription: { ru: "Создается под локацию, время доставки и характер события.", en: "Created around the location, delivery timing and character of the occasion.", it: "Creata intorno al luogo, all'orario di consegna e al carattere dell'occasione." },
    exactPrice: 680,
    images: ["/assets/products/generated/white-villa-arrangement.png"],
    categories: ["bespoke", "table"],
    flowerComposition: { ru: "Сезонный подбор с крупными садовыми цветами.", en: "Seasonal selection with large garden flowers.", it: "Selezione stagionale con grandi fiori da giardino." },
    sizeDescription: { ru: "VIP-композиция.", en: "VIP arrangement.", it: "Composizione VIP." },
    careInstructions: care,
    seasonalDisclaimer,
    featured: false,
    available: true,
    madeToOrder: true,
    minimumLeadTimeHours: 72,
    seoTitle: { ru: "Гость виллы", en: "Villa Guest arrangement", it: "Composizione Ospite in Villa" },
    seoDescription: { ru: "VIP-композиция для вилл и отелей Комо.", en: "VIP arrangement for Como villas and hotels.", it: "Composizione VIP per ville e hotel sul Lago di Como." }
  },
  {
    id: "p-012",
    slug: "lake-commission",
    title: { ru: "Индивидуальный проект у озера", en: "Lake Commission", it: "Commissione del Lago" },
    shortDescription: { ru: "Флористический арт-объект по индивидуальному запросу.", en: "A floral art object by individual request.", it: "Un oggetto d'arte floreale su richiesta individuale." },
    fullDescription: { ru: "Подходит для предложений, фотосессий, мероприятий и адресных VIP-подарков.", en: "Suitable for proposals, photo sessions, events and highly personal VIP gifts.", it: "Adatto a proposte, shooting, eventi e regali VIP altamente personali." },
    exactPrice: 920,
    images: ["/assets/products/generated/blue-floral-box.png"],
    categories: ["bespoke", "events"],
    flowerComposition: { ru: "Флористический состав формируется после брифа.", en: "The floral composition is defined after a brief.", it: "La composizione floreale viene definita dopo il brief." },
    sizeDescription: { ru: "Индивидуальная инсталляция.", en: "Bespoke installation.", it: "Installazione su misura." },
    careInstructions: care,
    seasonalDisclaimer,
    featured: false,
    available: true,
    madeToOrder: true,
    minimumLeadTimeHours: 96,
    seoTitle: { ru: "Индивидуальный проект у озера", en: "Lake Commission floral art", it: "Arte floreale Commissione del Lago" },
    seoDescription: { ru: "Флористический арт-объект MUZA.", en: "A floral art object by MUZA.", it: "Un oggetto d'arte floreale MUZA." }
  }
];

export function getProduct(slug: string) {
  return products.find((product) => product.slug === slug);
}
